### ISSUE TITLE
Adding Apache Cordova members

### ISSUE THREAD

**Issue by brodybits** [xmldom/xmldom#10]
I would like to start adding some owners and members from Apache Cordova, starting with @timbru31.

My reason for taking co-ownership was to get xmldom published with the fixed license spec (see apache/cordova-common#122).

Some minor points:

- I think this project should not be considered formally part of Apache Cordova or even Apache itself due to both the different licensing scheme and inclusion of some outsiders (see __#9__). _Some implications that I can think of:_
  - I think we should not follow the formal maintenance process from Apache Cordova. _That means that any member of xmldom can propose and publish updates. In general, we should follow a standard process of discussing first but nothing formal. In case we **do** need to consider a more formal process, I think it should be discussed in #9 and we should give all active owners a chance to respond and aim for concensus._
  - _I think we should not impose any extra requirements that current and former xmldom maintainers have not already been following, unless we can reach consensus from all active owners._
- As I said in __#9__, part of my agreement with @kethinov is that this project would be maintained in the new xmldom org on GitHub.

**Comment by brodybits** [comment]
I have now invited @timbru31 as a co-owner of the xmldom org and the npm package.

**Comment by brodybits** [comment]
@timbru31 and I have both made our membership in the xmldom public so that our Cordova users can see that we are supporting and maintaining this hard fork project.

@timbru31 did also enable mandatory two-factor authentication for existing and new members of the new xmldom GitHub org, which I do fully support though with a minor concern if this may become a barrier for any previous xmldom maintainers if they do want to join this org. More comments coming in #5.

**Comment by karfau** [comment]
I suggest to close this one, since it seems to be resolved. Feel free to reopen if required.
