### ISSUE TITLE
meta: Collaboration rules & procedures - ??

### ISSUE THREAD

**Issue by brodybits** [xmldom/xmldom#133]
I think there is an open question if we should start adding any collaboration rules & procedures.

@karfau has already demonstrated both the dedication and sense of good practice that we as owners think are needed from trusted collaborators. I would say that in absence of any formally agreed procedures and practices to simply use the best individual judgment.

For example, we generally like to have each PR reviewed by another collaborator before merging. And it is *generally* best for maintainers to merge their own PRs. For example, @karfau should be the one to merge PR #132 upon final review & approval. I would favor a couple exceptions:

- If one maintainer is too busy, it is OK for another maintainer to approve and merge.
- Some really small maintenance chores should not wait for review.

Starting with @karfau, we would generally invite new collaborators as collaborators with "write" privs (committer, collaborator on issues, collaborator on PRs) before inviting to publish on npm or share co-ownership of the `xmldom` org.

I would favor a few more quick items:

- no private discussions unless absolutely necessary
- no more rules & procedures for collaborators than absolutely necessary
- no more rules & procedures for external contributors than absolutely necessary (that said, maybe we should consider adding a formal code of conduct someday ??)
- explore how much we can learn from other projects and if there is anything else we can share with other projects

I will raise another issue to discuss whether or not we should consider adding another collaboration channel.

---

P.S. From other discussions I suspect we will need to add some labels. I am not sure where and even how much this will need to be discussed.

**Comment by karfau** [comment]
Here is the first related topic.

https://github.com/xmldom/xmldom/pull/132#issuecomment-698600796
> Did you mean to merge this with a merge commit?

I think there are two ways that PRs are being landed in this repo: merge and sqash, right?
What are the expected/preferred criteria to apply for deciding between the two?
(Sorry for not asking that before clicking the button the first time.)

**Comment by brodybits** [comment]
There are actually 3 ways to land PRs from the web page, which I think are all documented on the GitHub help pages:

- merge commit (seems to be the default)
- squash commit
- rebase merge

I never do the rebase merge.

There is also a drop-down thing on the right part of the green merge button, to choose *how* to do the merge.

I think that merging in a squash commit would keep the history cleaner and show the PR number directly on the commit where all of the changes are made.

For example: if someone would do `git blame`, or view the "blame" on the web GUI, the commit message for each of the changes would (should) show which PR number the changes were made in.

This also went wrong for me in PR #86, as I said here: https://github.com/xmldom/xmldom/pull/86#issuecomment-653386283

I probably should have made this more clear.

**Comment by karfau** [comment]
Sorry if that was not clear from my message. I know all the options and have used all of them before, but wanted to know which ones should be used in this repo for which reason.

Do I understand correctly that we prefer to always squash?
Sorry for no longer being aware that the merge commit happened by accident.

If we only want to allow one or two of them we can disable the others in the settings. This way it can not happen by accident.

PS: I tend to use rebase when it is important to keep the commits also when it lands on master. But it's a rare case. E.g. to preserve change history when renaming files.

**Comment by brodybits** [comment]
> Do I understand correctly that we prefer to always squash?

I would prefer to squash in almost all cases. As I said before, the squash commit generally shows the PR number more directly associated with the changes. But that is just me.

I would personally prefer merge commit over rebase, since merge commit would show the PR number in the history.

OTOH I think that GitHub will show the PR number of all changes whenever possible in the web GUI.

But as I tried to say before, I think that all of my points should be open for discussion.

**Comment by karfau** [comment]
Just discovered what Github offers in terms of public communication option, it was announced in May:
https://github.blog/2020-05-06-new-from-satellite-2020-github-codespaces-github-discussions-securing-code-in-private-repositories-and-more/#discussions

And here is one example where it's in action:
https://github.com/davidkpiano/xstate/discussions
(I discovered it, [because the "New Issue" categroy "Question" is configured to "redirect" to create a new discussion](https://github.com/davidkpiano/xstate/blob/master/.github/ISSUE_TEMPLATE/config.yml).)

**Comment by karfau** [comment]
By creating https://github.com/xmldom/xmldom/discussions/296 I hope to create a more open, vivid and encouraging discussion on all the related topics.

I think some details in this issue are still valuable, but I would rather link to it or copy stuff from here when it makes sense.

I would argue that this issue could be closed, since there is no clear level of done and anything that I would consider still worth wile should ideally be covered in the new (open ended) discussion.
