### ISSUE TITLE
meta: collaborator discussion channels

### ISSUE THREAD

**Issue by brodybits** [xmldom/xmldom#134]
As I said in #133, I think we should keep collaborator discussions public as much as possible.

I think GitHub discussions would be better than GitHub issues, but did not find a way to enable the discussions at this point. I suspect this will be possible within 6 months at the most.

Other possibilities include Slack, Gitter, Spectrum Chat, Rocket Chat, and Discourse. Here are my thoughs:

- Slack seems to support browser with notifications, mobile app, dedicated desktop app, and email notifications. Downside is lack of old chat history for free accounts, which leads me to -1 vote.
- Gitter supports browser with notifications, mobile app, and email notifications.
- Spectrum Chat supports browser (not sure about notifications), unsure about mobile app or email notifications. Spectrum seems to be part of GitHub now.
- Rocket Chat supports browsers (I am guessing with notifications), unsure about mobile app & email notifications. Rocket Chat has open source solution.
- Discourse supports browsers with notifications & email notifications, and it is open source. It may make sense to set up our own forum on the Discourse org. Discourse seems to be resource hungry, which leads me to -1 vote.

**Comment by karfau** [comment]
Discussions have been enabled and I hope that any further suggestions will originate from there and from the need for more than discussions have to offer.

Closing this for now.
