### ISSUE TITLE
MIT license is not complete

### ISSUE THREAD

**Issue by j-buckland** [xmldom/xmldom#173]
# Issue
An MIT license usually includes a copyright statement. The template which is linked to here https://github.com/xmldom/xmldom/blob/master/LICENSE.md is only a template. Most libraries I've seen use a LICENSE file with the copyright details filled in (see [restify](https://github.com/restify/node-restify/blob/master/LICENSE) as an example.

# Proposed solution
It would really help to be able to link to a file in your repo with the complete license text to make attributing and open source acknowledgements easier.

**Comment by brodybits** [comment]
I would favor dropping the LPGL option, as I said in #172, and using the standard MIT text in the license file.
