### ISSUE TITLE
Changelog for 0.5.0 not mentioning BREAKING

### ISSUE THREAD

**Issue by karfau** [xmldom/xmldom#196]
Some of the changes in 0.5.0 are breaking changes, so we should mention that.

**Comment by brodybits** [comment]
Good catch. Do you want to propose the change?

And I think we should make the 0.5.0 release on GitHub.

I am getting ready to take my rest soon. @karfau please feel free to take care of these things, I think there is no need for me to review. Otherwise I can do this later today.

**Comment by karfau** [comment]
Yes, I plan to add a PR for it. Just wanted to make you aware before we publish it.

**Comment by brodybits** [comment]
I took the liberty to publish 0.5.0 release on GitHub, with BREAKING CHANGE note added. My understanding is that it should be no problem for us to edit it if needed.

**Comment by karfau** [comment]
I'll check which one will be used by Dependabot/Renovate. Not so sure if we should actually maintain it in two places.

I updated the release description and filed #197 .
Of course we also need to add the information about #168 to the changelog, but I was not sure we want to do both changes in one PR. Feel free to add those lines to the PR if you think it's helpful.
