### ISSUE TITLE
'<' and '>' are not escaped in attribute values

### ISSUE THREAD

**Issue by zy-serguei** [xmldom/xmldom#198]
Serializer does not escape < and > characters in attribute values
`const doc = new DOMParser().parseFromString('<a a="&lt;&gt;"/>');`
`const result = new XMLSerializer().serializeToString(doc);`
result is `<a a="<>"/>`, which is invalid xml

**Comment by karfau** [comment]
@zy-serguei thx for reporting.

Just some details about why I didn't also add escaping for `>`:

According to the specs I linked in the PR, the `<` not being part of attribute values is a well-formedness constraint (so it's not about validity of the XML). 
But this is not true for `>` in attribute values, or at least I couldn't find anything about it.

We are dealing with similar issues in the same way, see #58 .

**Comment by retorquere** [comment]
> According to the specs I linked in the PR #199, the `<` not being part of attribute values is a well-formedness constraint (so it's not about validity of the XML). But this is not true for `>` in attribute values, or at least I couldn't find anything about it.

Is there a way I can force escaping of `>` in attribute values? Right now the behavior of this package gives us different output than when we use the parser/serializer in Firefox.

**Comment by karfau** [comment]
@retorquere No, there is no such option at the moment.

Please add any relevant information that is not already part of the discussion to #58, since this issue has already been closed.
