### ISSUE TITLE
Travis CI not working

### ISSUE THREAD

**Issue by brodybits** [xmldom/xmldom#2]
https://travis-ci.org/xmldom/xmldom

does not seem to see any branches that I push or any PR such as #1

I did get a single build to start by manual trigger, which I really do not like.

There seems to be an issue due to coverage, which I can look at once we get Travis CI working.

**Comment by brodybits** [comment]
Travis CI seems to be working with PRs now. But it seems stuck with coveralls.io which I would like to disable for now and deal with another day (#3).

For some reason every attempt on Travis CI seems to keep using coveralls.io. I really do not understand this!

**Comment by brodybits** [comment]
I raised this topic on the Travis CI forum: https://travis-ci.community/t/travis-ci-build-stuck-with-failure-on-coverage/6566

I hope to get the build working soon.

**Comment by timbru31** [comment]
The CI runs Node.js v0.10 - no wonder it's broken. Nevertheless, looking at the test script it seems a problem here:

`curl 'https://www.prettyrobots.com/travisty' | sh`.
Which is 
1. very scary to pipe a random script from cURL into sh
2. down (404) - probably resulting in the CI failure.

**Comment by timbru31** [comment]
Follow-up:  
IMO we should

- Drop old Node.js versions (#12)
- Upgrade the proof dependency and re-do the testsuite
- Update TravisCI matrix to run recent Node.js versions on all operating systems
- Refactor the test script not use shell at all and remove the `travisty` thingy

**Comment by brodybits** [comment]
Thanks @timbru31!

I just raised couple quick fix PRs, quick review would be much appreciated:

- #15 - change environment variable to give us a green build
- #16 - remove the extra curl command

I would definitely agree with dropping old Node.js versions, updating the proof dependency, and updating the Travis CI matrix. We would of course have to do this in another new 0.x release (unless we make a 1.0.0 release, which would be a whole other discussion), more comments coming in #12.

Refactoring the test script would be another whole other discussion if someone has time to look into it. I suspect there would be multiple things worth fixing if we decide to go through some refactoring efforts.
