### ISSUE TITLE
parse ref Attribut

### ISSUE THREAD

**Issue by scandinave** [xmldom/xmldom#21]
HI, 
Is there a way to get the type of an attribute that have a ref attribute.
Something like this : 
`<xs:attribute ref="xml:id" use="optional"/>`

It's defined with :

```
<xs:import namespace="http://www.w3.org/XML/1998/namespace"
		schemaLocation="xml.xsd"/>
```

**Comment by karfau** [comment]
xmldom is currently only processing a single XML file at a time.
But if you now how to read those fields and parse both files you should be able to get the right value by using the DOM Level 2 API as documented in the Readme.

Is that answering your question?

PR with a more concrete example added, even if not complete are welcome.

**Comment by karfau** [comment]
Closing, since there was no reply for quite a while.
