### ISSUE TITLE
[Security] now published as @xmldom/xmldom

### ISSUE THREAD

**Issue by karfau** [xmldom/xmldom#271]
# &TLDR;

We published 0.7.0 to npm as [`@xmldom/xmldom`](https://www.npmjs.com/package/@xmldom/xmldom) and will continue to publish updates there.
To get the security update, you have to switch the package you use in your `package.json`.

["quick post-mortem" by @brodybits](https://github.com/xmldom/xmldom/issues/271#issuecomment-902249697)

# Original Summary

To update the library to the newest version including the latest security fix you will have to [install to from the github repo or download the artifact from the github release and install it locally](https://github.com/xmldom/xmldom/discussions/270#discussioncomment-1080132).

For details of how to do that and asking questions please use [the related discussion](https://github.com/xmldom/xmldom/discussions/270)

We have filed a ticket at the npm support team addressing the issue.

We will Post updates about the current status here but lock this issue to only allow additions by maintainers, to allow people to subscribe and get informed when something changes.

**Comment by karfau** [comment]
> GitHub (GitHub Support)
> Aug 5, 2021, 1:39 PM UTC
> 
> Christian,
> 
> We are investigating your issue.
> 
> Thank you for your patience,
> npm engineering

---

>  GitHub (GitHub Support)
> Aug 5, 2021, 6:25 PM UTC
> Hi Christian,
> 
> Thanks for reaching out.
> 
> We are currently unable to find any documentation or transactions, to confirm the unscoped xmldom package was previously owned by `@xmldom` org.
> 
> Please forward any supporting document or communication for the package ownership. Once received, we'll review your request to transfer the package to xmldom org.
> 
> Best.
> 
> Judith
> GitHub Support

---

I replied today (6th of August)

Hello Judith,

I just checked `npm info` for the different xmldom versions:
The members of the npm xmldom org released all versions since 0.1.29.

The last release that was published by the maintainers listed on the npm website (jinjinyun and jindw) was 0.1.27 in November 2016

We documented the transition in our [changelog](https://github.com/xmldom/xmldom/blob/master/CHANGELOG.md#maintainer-changes), which is shipped with the packages since 0.3.0 (the linked section since 0.4.0).

Just in case this isn't enough, I Cced Chris Brody so he can reply with some reference of the mail conversation that lead to npm providing access to the package back then, in case it's still available.


Best,
Christian

**Comment by karfau** [comment]
Just to clarify that there was a misunderstanding from my side, I'm adding here the reply that @brodybits  added a day after my response:

> Hello I would like to add some context with a correction, adding one of the former publishers in CC.
> 
> Back in December 2019 I sent a request to all xmldom package owners at the time with CC to npm support to find a way to get xmldom updated on npm.
> 
> In response to my request, Eric Newport AKA kethinov added me to the xmldom package on npm.
> 
> I created the xmldom org on GitHub and started publishing updates from this project: https://github.com/xmldom/xmldom
> 
> I have also registered xmldom as an org on npm: https://www.npmjs.com/org/xmldom
And I have obtained both xmldom.com and xmldom.org.
> 
> Our plan was to keep the xmldom package updated from https://github.com/xmldom/xmldom and consider splitting xmldom into smaller parts in the `@xmldom` namespace as discussed in this issue: https://github.com/xmldom/xmldom/issues/54
> 
> As a next step, I will send a copy of the conversation I had with Eric Newport and npm support to start updating the package back in December 2019.
> 
> Chris

**Comment by karfau** [comment]
We just received an answer:

>  GitHub (GitHub Support)
Aug 9, 2021, 10:17 AM UTC
> 
> Hey,
> 
> sorry this is taking so long. I'll try to get you at least publish access for 'karfau' and 'brodybits' to be able to post an update today (hopefully next few hours) and will also push to get the package transferred to your org (including the xmldom-alpha so you can deprecate it).
> 
> Stefan

**Comment by karfau** [comment]
Another update:

>  GitHub (GitHub Support)
> 
> Aug 9, 2021, 7:21 PM UTC
> 
> Update: It's sadly not as easy as I had hoped.
> 
> I talked with the Trust & Safety team of GitHub today and they will take a look at this soon. This might take a bit. Sorry.
> 
> I'll keep this issue updated.
> 
> Stefan

**Comment by karfau** [comment]
FYI: I'm personally not able to check/respond to mails before the 16th or 17th of August.
(There has not been any update from github/npm side since my last message.)

**Comment by brodybits** [comment]
In that case, I will watch the mails from npm support and take action if appropriate.

**Comment by karfau** [comment]
>  Christian Bewernitz
> Aug 16, 2021, 8:15 PM UTC
> 
> `@npm`/`@github`
> 
> It has now been 20 days since we published the security advisory for the library that is (directly) used by 2.5k libraries out there.
> 
> And it has been 7 days since we last heard "something" from you:
> 
> > I talked with the Trust & Safety team of GitHub today and they will take a look at this soon. This might take a bit. Sorry.
> 
> Is there any progress on the topic? Can you give any ETA how long you will need / try to do something about it?
> 
> 
> Best
Christian

---

> GitHub (GitHub Support)
> Aug 17, 2021, 8:23 PM UTC
> 
> Hey xmldom team!
> 
> We’ve reviewed the situation with Trust and Safety and determined that unless the original maintainer decides to return access to the package, we will not be able to help with publishing the security update.
> 
> While we are not able to arbitrate disputes between package maintainers, we did want to ensure the original maintainer was aware of the security release your team is wanting to do. As such, we have reached out to @jindw regarding the release and will let you know if we receive a response.
> 
> I know that this is a disappointing outcome, but as stewards of the registry we need to be extremely careful about how we handle the packages we are responsible for. As outlined in our policies, we do not transfer abandoned packages, and taking over this package would set a very dangerous precedent.
> 
> https://docs.npmjs.com/policies/disputes#when-not-to-use-this-process
> 
> Please let us know if you have any questions.
> 
> Judith
> GitHub Support

Since we already attempted to contact/involve @jindw on the 9th of August

> Hey jindw,
> 
> I'm writing to you in the context of https://github.com/xmldom/xmldom/issues/271, since we are trying to publish a fix for an already published security advisory to the npm registry.
> 
> Since your npm and github profiles show recent activity in the recent months, I thought it would be a good idea to ask you:
> Do you know why all the maintainers of the recent years recently lost their right to publish the xmldom package?
> Can you please help us to restore those rights for at least one of kethinov, timbru31, brodybits, karfau?
> 
> I hope we can find a fast solution to finally make the fix available via npm and to also resolve any potential issues regarding access in the near future.
> 
> 
> Best regards,
> 
> Christian Bewernitz
> aka karfau

and didn't hear back anything from him so far, we will not bet on this issue being resolved any time soon.

This means we will need to decide on the new name under the `@xmldom` scope and publish it.

**Comment by karfau** [comment]
We will soon publish the fixed version under the `@xmldom` scope to npm, the "fully qualified name" of the library will switch to `@xmldom/xmldom`. For details see #278

**Comment by karfau** [comment]
v0.7.0 is not available as https://www.npmjs.com/package/@xmldom/xmldom.

The only way to ever publish `xmldom` again, would be if the original maintainer restored access or transferred the package to the related npm org.

So I think it's reasonable to close this issue.

Just in case somebody disagrees I will unlock the conversation.
Please only reply here related to this specific issue, for anything else post in #270 or create a new discussion/issue.
Thank you for your patience.

**Comment by PCOffline** [comment]
Will this package have a deprecation warning, in case of failure to establish contact with the original developers?

**Comment by kachkaev** [comment]
Thanks for resolving the publishing issue folks! It's hard to imagine how overwhelming it must have been 😞

I wonder what’s best to do with the typings. There exists [`@types/xmldom`](https://www.npmjs.com/package/@types/xmldom) with 180K downloads per week, which does not fit the new package. It is possible to publish `@types/xmldom__xmldom` instead, thus keeping the types outside the library.

But maybe it's a good opportunity to bring the declarations in? We'll need to copy [`index.d.ts`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/77c14c8d4a8e09ed69b6a3218f2dd8c2f472ca78/types/xmldom/index.d.ts) and mention it in `package.json`. Library users will get the typings out of the box without having to add an extra dependency. The downside of this approach is that maintainers will have to review potential type enhancements and release them as new  patch versions of `@xmldom/xmldom`. Given that the library is stable, this should happen quite rarely.

Happy to help with a PR if you're up for the built-in typings. WDYT?

**Comment by karfau** [comment]
@PCOffline As far as I know, only owners can deprecate their packages, so there is nothing we can do about it:
```
$ npm owner ls xmldom
jinjinyun <jinyun.jin@gmail.com>
jindw <jindw@xidea.org>
```

But since our security advisory points to the `xmldom` package, the security warnings might pull some people over.

**Comment by karfau** [comment]
@kachkaev let's please continue that discussion in #191

**Comment by brodybits** [comment]
I am posting a quick post-mortem here. I already added some relevant info to this comment: https://github.com/xmldom/xmldom/issues/271#issuecomment-894777117

I would like to emphasize this statement I made in our conversation with npm support:

> Our intention was to work together with the previous owners if they wanted, NOT for xmldom to become fragmented between GitHub and npm as it is now.

I am hopeful that updating the info in `readme.md` like we did in PR #278 will help avoid confusion moving forward.

We probably should have removed the inactive people from the npm package when we started making the security updates, blame is on myself for overlooking this.

It looks like npm decided to start changing the policy for abandoned packages: https://github.com/npm/roadmap/issues/28

https://github.com/npm/roadmap/issues/28 indicated to me like they were planning update the policy again, but the recent updates from npm support make this sound unlikely.

Unfortunately this could lead to an increasingly growing graveyard of popular but abandoned packages in the npm ecosphere (abandonware), and with an unfortunate risk of random security holes coming everywhere. Very, very unfortunate for trust in the npm ecosphere !!

**Comment by brodybits** [comment]
I think we should pin a new, unlocked issue with a clear statement that this package is now published as `@xmldom/xmldom`. I can anticipate a number of users and projects encountering bugs and security issues with the existing xmldom package and coming here for help. What do you think @karfau? Do you want to do this?

**Comment by karfau** [comment]
@brodybits that is why I added the tldr section to the issue description.

We could of course additionally/further rephrase the title?

For my taste we already have enough conversation channels open regarding this release...

In case you are still sure your suggestion drastically improves the situation by tomorrow, just go ahaed.

**Comment by brodybits** [comment]
> We could of course additionally/further rephrase the title?

Done, please feel free to update again

> For my taste we already have enough conversation channels open regarding this release...

Agreed, I started thinking the same thing as well.

I am reopening for now with the updated title, tldr looks good to me.

The one thing I don't like about long-running issues & PRs is that GitHub seems to auto-hide some parts.

This seems to have affected quite a few downstream projects. I do remain hopeful that we will see a better solution ... someday.

**Comment by karfau** [comment]
@brodybits It's not clear to me what you are trying to communicate with the new title.
Is it something like "This package is now published as `@xmldom/xmldom`!"

And how/when will we ever resolve/close this issue?

I wouldn't care as much if the issue wouldn't be pinned, but I think it's a good idea to pin it, we should just be clear (as in easy to understand) about the status and level of done.

**Comment by brodybits** [comment]
@karfau I made another quick update to the title ... please feel free to update again as you see to be appropriate. Closing now (keeping this pinned). What a pain this has been :-(

**Comment by karfau** [comment]
@brodybits Thanks a lot for your ongoing support during all of this!

**Comment by dj-documentation** [comment]
https://github.com/videojs/mpd-parser/issues/143

**Comment by dj-documentation** [comment]
https://github.com/videojs/video.js/issues/7389

**Comment by ryankashi** [comment]
Hi there! This may be a bit of a stupid question. I have a number of packages that I use that require xmldom as one of **their** dependencies. How would I go about upgrading the internal dependencies of my packages with the newly upgraded xmldom?

**Comment by ku18am** [comment]
> Hi there! This may be a bit of a stupid question. I have a number of packages that I use that require xmldom as one of **their** dependencies. How would I go about upgrading the internal dependencies of my packages with the newly upgraded xmldom?

I am using [npm-force-resolutions](https://www.npmjs.com/package/npm-force-resolutions) 
just need to make two changes at your package.json

**Comment by joebowbeer** [comment]
> Hi there! This may be a bit of a stupid question. I have a number of packages that I use that require xmldom as one of **their** dependencies. How would I go about upgrading the internal dependencies of my packages with the newly upgraded xmldom?

File an issue and/or create a PR in the project that depends on xmldom.

@ku18am Can npm-force-resolutions change the package name in addition to the version?

**Comment by PCOffline** [comment]
> > Hi there! This may be a bit of a stupid question. I have a number of packages that I use that require xmldom as one of **their** dependencies. How would I go about upgrading the internal dependencies of my packages with the newly upgraded xmldom?
> 
> I am using [npm-force-resolutions](https://www.npmjs.com/package/npm-force-resolutions)
> just need to make two changes at your package.json

Don't use npm-force-resolutions. Use [force-resolutions](https://www.npmjs.com/package/force-resolutions) instead. It is a more supported package and doesn't fail when package-lock file is missing.

**Comment by joebowbeer** [comment]
Also note that running force-resolutions in this way, via npx, exempts it and its dependencies from any threat analysis. In essence you are trusting it as much as you trust node itself.

**Comment by karfau** [comment]
I agree we are talking about a workaround, everybody can contribute to raise awareness or even helping people to switch by filing PRs. The faster downstreams switch the better.

Regarding the workaround:

I don't know about the details of `force-resolution` but since there are quite some outdated dependencies out there using `xmldom` and even already deprecated versions of it, it might be worth documenting it as a strategy.

In npm you can write the following in a dependency block of package.json:
```json
{
  "dependencies": {
    "xmldom": "@xmldom/xmldom@0.7.3"
  }
}
```
This way the package would be installed under `node_modules/xmldom` and can be imported as `xmldom`. If that also works with `force-resolution`, it could be the/one way to go.

@joebowbeer 
> Also note that running force-resolutions in this way, via npx, exempts it and its dependencies from any threat analysis. In essence you are trusting it as much as you trust node itself. At the very least, specify an exact version of force-resolutions to run.

Could that be solved by adding @xmldom/xmldom` as a top level dependency/devDependency in your project to make sure all the usual scanning and update mechanisms apply?

**Comment by joebowbeer** [comment]
Running audit after running force-resolutions should audit what is installed.

I always recommend using a specific version instead of latest, e.g.:

`npx force-resolutions@1.0.6 `

**Comment by karfau** [comment]
Great news: [renovate offers replacement presets](https://docs.renovatebot.com/presets-replacements/) that are included in the default config, and we have been able to contribute such a preset that should help people/project that use renovate to update dependencies to make the switch: https://github.com/renovatebot/renovate/pull/15588
(It was just released.)

I really curious how those PRs will look. In case you spot one anywhere, please post a link here :).

I'm expecting this will finally reduce the number of people that are stuck on the old package.
