### ISSUE TITLE
Provide usage examples for `XMLSerializer` & `DOMImplementation`

### ISSUE THREAD

**Issue by brodybits** [xmldom/xmldom#31]
The current usage example in the `readme.md` only shows how to import and use the DOM parser.
We should also provide examples for the other main exports that are listed in the first section. 

e.g. (as a starting point)

```js
const XMLSerializer = require('xmldom').XMLSerializer
```

or simply

```js
const { XMLSerializer } = require('xmldom')
```

and

```js
const { DOMImplementation } = require('xmldom')
```

We should also add a test for the exact code we provide as examples, [to make sure the examples do not break](https://dev.to/burdettelamar/keep-your-example-code-green-4b7e) ideally in an own spec file that has a comment to make sure it is in sync with the readme file. (It's not required to automate including the examples into the README!)

**Comment by karfau** [comment]
This was resolved in 0.8.2, the exaamples live in the `examples` directory and are also tested as part of our github actions workflow, see #317
