### ISSUE TITLE
test coverage seems to be very limited

### ISSUE THREAD

**Issue by brodybits** [xmldom/xmldom#35]
`npm test` continues to succeed if I make some non-sense edits in my work area:

```diff
% git diff      
diff --git a/lib/dom-parser.js b/lib/dom-parser.js
index 92937fd..1726488 100644
--- a/lib/dom-parser.js
+++ b/lib/dom-parser.js
@@ -246,6 +246,6 @@ function appendElement (hander,node) {
 var htmlEntity = require('./entities');
 var XMLReader = require('./sax').XMLReader;
 var DOMImplementation = exports.DOMImplementation = require('./dom').DOMImplementation;
-exports.XMLSerializer = require('./dom').XMLSerializer ;
-exports.DOMParser = DOMParser;
+//exports.XMLSerializer = require('./dom').XMLSerializer ;
+//exports.DOMParser = DOMParser;
 //}
diff --git a/lib/dom.js b/lib/dom.js
index 01794c8..5ffcf27 100644
--- a/lib/dom.js
+++ b/lib/dom.js
@@ -1250,7 +1250,7 @@ try{
 }
 
 //if(typeof require == 'function'){
-       exports.Node = Node;
-       exports.DOMImplementation = DOMImplementation;
-       exports.XMLSerializer = XMLSerializer;
+       //exports.Node = Node;
+       //exports.DOMImplementation = DOMImplementation;
+       //exports.XMLSerializer = XMLSerializer;
 //}
```

I think we need to massively improve the test suite before we can do much more cleanup work.

**Comment by brodybits** [comment]
I have been using Stryker Mutator on some other projects, highly recommended we consider using it for xmldom.

**Comment by brodybits** [comment]
I would personally be very open to switching from proof to a well-known test library or framework. I generally like to use Jest in new projects since it just works for both normal JavaScript projects and React Native. I would also not mind adding the new test library before dropping use of the existing `proof` testlib. This could help unblock testing for PRs like #41.

**Comment by karfau** [comment]
I'm very interested in supporting this. any specific tasks/what would be a good first test to have (in a new test framework)?
I have some experience with `mocha`, `tap` and `jest` but none with `proof`.

**Comment by brodybits** [comment]
I would start with adding test coverage for the cases in the description.

I think it would be ideal if someone could get Stryker Mutator working with this project.

In terms of test framework, I would probably favor Jest in first place. Jest seems to be used almost always in React Native projects, used in Prettier, and I have come to really like using it. Tap also looks really nice, it looks like it starts with a relatively simple core based on Tape and can be extended with some nicer reporters.

**Comment by karfau** [comment]
Wow, I just realize that all the code in the `test` directory is just some code that dumps stuff to the CLI. No assertions.
And the only test that is tested using `proof` is that `lib/dom-parser.js` is thruthy...

**Comment by karfau** [comment]
I think going for `jest` will lower the barrier of enrty for may people, which could come in handy in our situation.
And with snapshot testing we could at least assert that it produces the same results that it did before the fork added any changes.
I will give it a try.

**Comment by karfau** [comment]
I just found https://github.com/jindw/xmldom/issues/138 saying there is an issue with using xmldom in combination with `jest`. Maybe it has been fixed already on the jest side, or we will learn something interesting about xmldom :smile:

**Comment by karfau** [comment]
I digged a bit into the details of testing SAX and existing sax parsers.

It could be worth wile to attempt jindw/xmldom/issues/16 (but there are some isues with it that make it hard).

Which brings me to the (big) question if it's a good idea to maintain both a(nother) SAX parser and all the DOM related things in this project. (I [have done](https://github.com/karfau/node-cli-arguments-options) the groundwork for comparing different libraries in an efficient manner before, this could be extended/replicated to compare SAX parsers.)

But I think at least having "tons of" fixtures that are checked without writing "tons of" manual tests  is a good idea to [verify compatibility with DOM specs](https://github.com/jindw/xmldom/issues/15). 
- either we just find a way to produce XML fixtures and process them
- or we find a way to generate tests for the API

Any thoughts on this?
(Should we create extra issues for that to communicate intent?)

**Comment by brodybits** [comment]
Thanks @karfau. I would definitely favor discussing Jest, library comparisons, and DOM specs in separate issues.

There may be some better libraries out there, but I think some projects will continue using xmldom for quite a while (if it ain't broke ...). I got into maintaining the xmldom package since it is used by plist and hence by cordova-ios packages.

**Comment by brodybits** [comment]
@karfau I just raised #54 & #55 based on your comments.
