### ISSUE TITLE
General cleanup - should be released before 1.0.0

### ISSUE THREAD

**Issue by brodybits** [xmldom/xmldom#37]
I think we should do some general cleanup of the code. I already noticed quite a few things related to import and export of modules (see PRs #28 & #36) and standard(ized) formatting needed (issue #29). This should definitely be done and released before we consider stable 1.0.0 release.

**Comment by karfau** [comment]
For me it looks like a most things mentioned are covered by other issues or PRs and I don't see how having such "umbrella" issue helps us.
