### ISSUE TITLE
Implement the selectors API

### ISSUE THREAD

**Issue by codler** [xmldom/xmldom#39]
See https://github.com/jindw/xmldom/issues/98

**Comment by brodybits** [comment]
Thanks. I think it would be ideal if we can make and release this feature before we consider stable 1.0.0 release (see milestones [here](https://github.com/xmldom/xmldom/milestones)).

**Comment by karfau** [comment]
I would currently consider this out of the scope if this library since it's not part of the Spec that xmldom currently is trying to provide (and still struggling with).

See #92
