### ISSUE TITLE
Wrong format after InsertBefore

### ISSUE THREAD

**Issue by prorok-kane** [xmldom/xmldom#402]
If I add an element to my document, the final output is wrong formatted. The result is not valid I think.

Original XML
```
<xml xmlns:xi="http://www.w3.org/2001/XInclude">

   <vars>
....
```
Changed XML
```
<xml xmlns:xi="http://www.w3.org/2001/XInclude">

    <TCafe initvalue="1" type="int"/><vars>
```
Expected XML
```
<xml xmlns:xi="http://www.w3.org/2001/XInclude">

    <TCafe initvalue="1" type="int"/>

       <vars>
```

Code
```
var DOMParser = require('xmldom').DOMParser;
var serializer = new (require('xmldom')).XMLSerializer;

var xmlDoc = new DOMParser().parseFromString(dataRegelWerk);

            if(allok == false){

                var root = xmlDoc.documentElement;
                var varselem = xmlDoc.getElementsByTagName("vars")[0];
                var newEle = xmlDoc.createElement("TCafe");
                var att1 = xmlDoc.createAttribute("initvalue");
                att1.value = "1";
                var att2 = xmlDoc.createAttribute("type");
                att2.value = "int";
                newEle.setAttributeNode(att1);
                newEle.setAttributeNode(att2);
                root.insertBefore(newEle, varselem);

            }

            var myFile = serializer.serializeToString(xmlDoc);


            fs.writeFileSync(filePath,myFile,{encoding:'utf8',flag:'w+'});
```

**Comment by karfau** [comment]
I added triple back ticks around your code snippets and XML, to make them visible.

The part of the original XML that you added is incomplete so it is not valid, but lets assume it is, becsuse the elements you show are closed as part of `...`.

The only difference I can spot between the "changed" and the "expected" is whitespace between two sibling tags. Which doesn't have to do anything with the validity.

And like others have found out, [xmldom currently doesn't support pretty printing](https://github.com/xmldom/xmldom/issues/44)

(If the additional indentation should indicate that you expect the `vars` tag to be a child of the added element, you misunderstood the meaning of `insertBefore`.)

In case there is anything I misunderstood, please let me know.
