### ISSUE TITLE
Compress files error by UglifyJs

### ISSUE THREAD

**Issue by fengxinming** [xmldom/xmldom#453]
ES6 syntax is mixed in the ES5 syntax code

** 0.8.4 **
![image](https://user-images.githubusercontent.com/6262382/198938272-2be9016f-d815-493f-8663-6e2d57341bf1.png)

** 0.7.7 **
![image](https://user-images.githubusercontent.com/6262382/198937827-061b8fa5-89cc-4e06-af4f-e91212a7ef09.png)

**Comment by karfau** [comment]
Thank you for reporting it. I already started working on a fix, will land and publich the fixes within the next 24hours.

**Comment by karfau** [comment]
FYI: 0.9.0-beta.5 and 0.8.5 have been released, 0.7.8 will follow in the evening.

**Comment by karfau** [comment]
Update: 0.7.8 also has been released.
