### ISSUE TITLE
getAttribute() doesn't return null for not existing attributes

### ISSUE THREAD

**Issue by domekomi** [xmldom/xmldom#46]
`getAttribute()` and related methods don't return null for not existing attributes.
Methods below should be fixed to return null.

* NamedNodeMap.prototype.getNamedItem()
* Element.prototype.getAttribute()
* Element.prototype.getAttributeNode()
* Element.prototype.getAttributeNS()

**Comment by zhiqingchen** [comment]
"@xmldom/xmldom": "0.8.2",
Also have this problem

**Comment by karfau** [comment]
Reopeneing this since I'm still working on it in #482
