### ISSUE TITLE
Disable Error [ParseError]: Attribute id redefined

### ISSUE THREAD

**Issue by sahin52** [xmldom/xmldom#460]
**Is your feature request related to a problem? Please describe.**
I am trying to parse an HTML of a website which has some wrong with their html element, like id redefined. I dont need this area where the error is thrown but I need other areas
**Describe the solution you'd like**
There must be a way to disable these errors. Like browsers render the elements even though there are errors.
**Describe alternatives you've considered**
I am not sure but xml2 might have that option

**Comment by karfau** [comment]
1. Have you tried passing the html mime type for parsing? It is less strict, but from the top of my head I don't remember if your case is covered by that.

If 1 doesn't help: there is an option that you can use but it comes with a risk if the XML is user input (not controlled by you): you can provide an `errorHandler` to the DOMParser constructor that doesn't throw. This way everything will be attempted to be parsed. But don't rely on anything/ask for any support if strange thing happen ...

**Comment by karfau** [comment]
Closing it since there has not been any response since over half a year and the recommendation I gave is no longer valid in the upcoming 0.9.0 version
