### ISSUE TITLE
Add an option to XMLSerializer() for adding a space before closing self containing tags

### ISSUE THREAD

**Issue by MattrCoUk** [xmldom/xmldom#465]
**Is your feature request related to a problem? Please describe.**
After processing the XML file the elements such as `<tag />`  become `<tag/>` and `<tag attribute="value" />` become `<tag attribute="value"/>`. 

**Describe the solution you'd like**
For compatibility with older xml files such as some .net's **.csproj** files it would be nice to have an option to add a space before the tag closing.

**Additional context**
![image](https://user-images.githubusercontent.com/14859894/207058970-1e787ee8-a5d7-4a31-afb6-28197bc8000f.png)

**Comment by karfau** [comment]
Thx for requesting it. If you create a PR we can land it.
Even though I personally prefer to add the space by default, I'm not sure we should do that.
So an option would be nice.

**Comment by AnWeber** [comment]
I have also written an XML Formatter for myself that handles this requirement. You could try to integrate this back into xmldom. Alternatively you can use it directly yourself (https://github.com/AnWeber/xmldom-format/).

**Comment by MattrCoUk** [comment]
I agree with @karfau that this is not an essential feature as it should be fairly easy to just process the resulting string with something like `.replaceAll('/>',' />’)` if needed.

**Comment by karfau** [comment]
@AnWeber 
> I have also written an XML Formatter for myself that handles this requirement. You could try to integrate this back into xmldom. 

At the moment there are quite some things that make it impossible for me to integrate this code into xmldom.
Main one being that it is typescript.

But it is a great workaround that can be applied by those that need it.

@MattrCoUk do you think we can/should close this issue?

**Comment by MattrCoUk** [comment]
I’m ok with closing the issue @karfau Thanks
