### ISSUE TITLE
Entity not found

### ISSUE THREAD

**Issue by luckasRanarison** [xmldom/xmldom#466]
I got **"entity not found error"** on every line containing an entity when parsing the JMdict XML file, here is the link: http://ftp.edrdg.org/pub/Nihongo/JMdict.gz

Am I missing something or does xmldom not support this yet? 

**Sample output:**
 [xmldom error]  entity not found:&vt; 
@#[line:309191,col:1]
[xmldom error]  entity not found:&comp; 
@#[line:309192,col:1]
[xmldom error]  entity not found:&n; 
@#[line:309196,col:1]
[xmldom error]  entity not found:&vs; 

xmldom version: 0.8.6
runtime version: 16.18.1

**Comment by karfau** [comment]
Thx for asking.

Yes, xmldom is not parsing entities from DTD, it is only able to ignore them.
And due to the inherent complexity and the current quality of the parser code this will most likely not be implemented any time soon.

**Comment by karfau** [comment]
And here is a longer thread on the topic: https://github.com/xmldom/xmldom/issues/117
