### ISSUE TITLE
Expose DOM Implementation

### ISSUE THREAD

**Issue by dyn-dadeni** [xmldom/xmldom#48]
Is there some reason you chose not to expose your DOM implementation so it can be imported? I would like to write code that uses the instanceof operator to check if a node's constructor is of one type or another, but since none of the constructors of your DOM objects are exported, I can't do that.

I can't even use the NodeType enumeration in your dom-parser module to determine the node type because it isn't exported either.

**Comment by dyn-dadeni** [comment]
Also, I notice that Element doesn't inherit from Node, which is problematic.

**Comment by brodybits** [comment]
May be related to #40

**Comment by karfau** [comment]
( and it's related to #54 but not with a high impact)

**Comment by karfau** [comment]
Please add/subscribe to #40
