### ISSUE TITLE
DOMParser does not normalize line breaks

### ISSUE THREAD

**Issue by victorandree** [xmldom/xmldom#49]
If I parse an XML string containing newlines encoded as `\r\n` (`#xD #xA`), these are not normalized into `\n` (`#xA`). I think this violates the "[End-of-Line Handling](https://www.w3.org/TR/2008/REC-xml-20081126/#sec-line-ends)" section of the XML specification.

> To simplify the tasks of applications, the XML processor MUST behave as if it normalized all line breaks in external parsed entities (including the document entity) on input, before parsing, by translating both the two-character sequence #xD #xA and any #xD that is not followed by #xA to a single #xA character.

**Comment by karfau** [comment]
The more recent [XML1.1 Spec](https://www.w3.org/TR/xml11/#sec-line-ends) also contains such a section:

> XML parsed entities are often stored in computer files which, for editing convenience, are organized into lines. These lines are typically separated by some combination of the characters CARRIAGE RETURN (#xD) and LINE FEED (#xA).
> To simplify the tasks of applications, the XML processor must behave as if it normalized all line breaks in external parsed entities (including the document entity) on input, before parsing, by translating all of the following to a single #xA character:
> - the two-character sequence #xD #xA
> - the two-character sequence #xD #x85
> - the single character #x85
> - the single character #x2028
> - any #xD character that is not immediately followed by #xA or #x85.
> 
> The characters #x85 and #x2028 cannot be reliably recognized and translated until an entity's encoding declaration (if present) has been read. Therefore, it is a fatal error to use them within the XML declaration or text declaration.

**Comment by karfau** [comment]
We solved half of it as part of #303. I should not have created that duplicate...
