### ISSUE TITLE
breaking: fix main package entry

### ISSUE THREAD

**Issue by brodybits** [xmldom/xmldom#53]
The following `main` entry in package.json only exports `lib/dom-parser.js`:

```json
  "main": "lib/dom-parser.js",
```

I think the `main` package object should provide access to functionality of all modules in `lib`.

May be related to: #40, #48

**Comment by karfau** [comment]
To clarify the status: #233 deprecated the redundant exports in `lib/dom-parser.js`, they will be dropped from the module in the next breaking release, which will resolve this issue.
