### ISSUE TITLE
Regression regarding handling of `&nbsp;` with "(x)html" mimeType

### ISSUE THREAD

**Issue by karfau** [xmldom/xmldom#57]
As [discovered in #51](https://github.com/xmldom/xmldom/pull/51#issuecomment-647081281), when parsing `<body>&nbsp;word</body>` with one of the possible "(x)html" mimeTypes, already in the parsed object structure `nbsp;` has been replaced with a normal (breaking) space. When it's serielized it then returns `<body xmlns="http://www.w3.org/1999/xhtml"> word</body>`.

The regression was introduced in 6b47d09be5aca3e0b4687812dfccf452482bc660 ([that handels some cases correctly](https://github.com/xmldom/xmldom/commit/6b47d09be5aca3e0b4687812dfccf452482bc660#diff-b7abc4fd0b8aebd87eb1b0fce7e40a45R270-R272)) and it's impact was widened 56eb39f82dd2052a683b1870fb1f4a105e184f66
and first published as part of v0.2.0 ([github](https://github.com/xmldom/xmldom/releases/tag/0.2.0), [npm](https://www.npmjs.com/package/xmldom/v/0.2.0))

A fix is available in 908b9da2 but we want to first fix #35 and #56

**Comment by brodybits** [comment]
> The regression was introduced in [6b47d09](https://github.com/xmldom/xmldom/commit/6b47d09be5aca3e0b4687812dfccf452482bc660) ([that handels some cases correctly](https://github.com/xmldom/xmldom/commit/6b47d09be5aca3e0b4687812dfccf452482bc660#diff-b7abc4fd0b8aebd87eb1b0fce7e40a45R270-R272))

Looking at the changes, I have a feeling the `&nbsp;` functionality would not have worked at all before the changes were applied.

**Comment by karfau** [comment]
> > The regression was introduced in [6b47d09](https://github.com/xmldom/xmldom/commit/6b47d09be5aca3e0b4687812dfccf452482bc660) ([that handels some cases correctly](https://github.com/xmldom/xmldom/commit/6b47d09be5aca3e0b4687812dfccf452482bc660#diff-b7abc4fd0b8aebd87eb1b0fce7e40a45R270-R272))
> 
> Looking at the changes, I have a feeling the `&nbsp;` functionality would not have worked at all before the changes were applied.

Before 6b47d09b it was [only converted to `'\xa0'` in the case of some mime types](https://github.com/xmldom/xmldom/commit/6b47d09be5aca3e0b4687812dfccf452482bc660#diff-b7abc4fd0b8aebd87eb1b0fce7e40a45R270-R271), this behavior didn't change in this commit for those mime types since the condition was left in place. But in 56eb39f the condition was moved from the lines linked above to count for all cases where the new entity map was used. So only then it affected all matching mime types.
And maybe this description can be shortened if we find that both conditions are true for both conditions, but there are so many mime types, I didn't investigate further which ones it would have matched.

**Comment by brodybits** [comment]
> Looking at the changes, I have a feeling the `&nbsp;` functionality would not have worked at all before the changes were applied.

I take that statement back now. I had not seen `nbsp` in the `entityMap` object in the v0.1.27, finally found it here: https://github.com/xmldom/xmldom/blob/v0.1.27/dom-parser.js#L20

I did try a quick test program which does confirm to me that the regression was first published in 0.2.0, and that it is in fact fixed by PR #67:

```js
const { DOMParser } = require(`./${require('./package.json').main}`)

console.log(
  (
    new DOMParser().parseFromString(
      '<div>&copy;&nbsp;&copy;</div>',
      'text/html'
    ) + ''
  )
    .replace(/ /g, '{{space}}')
    .replace(/\u00a0/g, '{{nbsp}}')
)
```

Actually the regression does show up in `v0.1.28-xmldom-alpha` and `v0.1.28-xmldom-alpha~1`, presumably published by `xmldom-alpha`, but was (fortunately) never published on the `xmldom` package itself.

That the regression never affected `xmldom` pre-0.2.0 on npm demonstrates some of the power of patch maintenance branches.

**Comment by karfau** [comment]
@brodybits I think this needs to be part of the 0.4.0 milestone, so it ends up in the Changelog for that release.

**Comment by karfau** [comment]
@brodybits 
Related to #62 
As you can see above I took the liberty to file issues on all the remaining dependents of xmldom-alpha.
Current status:
- 1 repo closed the issue and was archived afterwards
- 1 repo showed me that they are already no longer using the xmldom-alpha in their beta version

That is why I also requested to add this issue to the current milestone. I took the liberty to take care of that on my own now.
