### ISSUE TITLE
Improve vows test assertions

### ISSUE THREAD

**Issue by brodybits** [xmldom/xmldom#61]
PR #59 is there to recover the original vows tests and fix the existing assertions. Some more improvements were originally proposed in PR #51. From PR #59 and maybe PR #51 I think there are some things we can do to further improve the assertions.

/cc @karfau

**Comment by karfau** [comment]
I think it would be good to define a "level of done" per issue, so it becomes obvious if a PR fixes an issue or only does it partially.
This ticket is only about the assertions in the vows test suites, right?
Meaning it might become obsolete when we have a more thorough test suite based on an up-to-date test framework (like jest).

I guess discussing how to strategically approach a new test suite would be another issue?

**Comment by karfau** [comment]
Vows is no longer an issue :tada: 
See #174
