### ISSUE TITLE
[feature-request] Make `Element::childNodes` and `Element::attributes` iterable

### ISSUE THREAD

**Issue by Ponynjaa** [xmldom/xmldom#633]
**Is your feature request related to a problem? Please describe.**
It's currently not possible to iterate over the childNodes or attributes of an element like this:
```javascript
for (const child of element.childNodes) {
    console.log(child.nodeName);
}

for (const attr of element.attributes) {
    console.log(attr.value);
}
```
instead you have to write it like this:
```javascript
for (let i = 0; i < element.childNodes.length; i++) {
    const child = element.childNodes[i];
    console.log(child.nodeName);
}

for (let i = 0; i < element.attributes.length; i++) {
    const attr = element.attributes[i];
    console.log(attr.value);
}
```

**Describe the solution you'd like**
Add a generator function like this:
```javascript
[Symbol.iterator]: function * () {
    for (var i = 0; i < this.length; i++) {
        yield this[i];
    }
},
```
to `NodeList` and `NamedNodeMap`.

**Describe alternatives you've considered**
I am currently polyfilling this in my own project that uses xmldom so I can use `for...of` loops.

**Additional context**
I already implemented this and opened a PR [here](https://github.com/xmldom/xmldom/pull/634).

**Comment by karfau** [comment]
Thank you for your contribution.
Do you happen to know if this is supported by the native browser implementation/DOM specs?

I'm hesitant to add anything to the DOM API that is not part of the spec.

I think there already is an internal helper method somewhere which could be exposed, or even published as a separate package in the xmldom org.
Will check the code.

If you don't know/want to look it up I will eventually figure it put myself, but I currently only have limited resources for this project.

**Comment by Ponynjaa** [comment]
I looked it up and I think it should be supported. At least it is supported in the native browser implementations for sure.
In the specs it only explicitly says `iterable<Node>` for [NodeList](https://dom.spec.whatwg.org/#interface-nodelist) but not for [NamedNodeMap](https://dom.spec.whatwg.org/#interface-namednodemap). However when looking it up on [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Element/attributes#enumerating_elements_attributes) it says that "you can enumerate through an element's attributes using for...of".

I'm not quite sure what you mean by exposing some kind of helper function, can you explain that please?

**Comment by karfau** [comment]
Thx for doing the research.
I agree that it is a very nice addition.
Since it is, we don't need to discuss any helper function stuff, that was meant as an alternative approach.
