### ISSUE TITLE
Whitespace (incl. line breaks) in closing tags are not parsed correctly

### ISSUE THREAD

**Issue by brodybits** [xmldom/xmldom#69]
- spaces in closing tags (<https://github.com/jindw/xmldom/issues/197>)
- spaces in empty tags, for example: `<my-element />`, `<my-element option="value" />`
- spaces in opening tags

Maybe some of there are already covered, needs investigation.

/cc @karfau

**Comment by karfau** [comment]
Yes, (single) spaces in opening tags and empty tags [are covered by some tests](https://github.com/xmldom/xmldom/blob/8a31e94596f4f38a2cccf6a63df57108d63b7c37/test/parse/parse-element.vows.js#L10-L32).

A quick check shows:

`'<root></root >' => '<root/>'` :relieved: 

**but** the example from the ticket:

`'<book></book ><title>Harry Potter</title>' => '<book><title>Harry Potter</title></book >'` :fearful: 

where the following (just the space removed)

`'<book></book><title>Harry Potter</title>' => '<book/><title>Harry Potter</title>'` :relieved:

works as expected.
This sure needs some investigation.

And a future proof way to write tests, see #72 .

**Comment by karfau** [comment]
I think there is nothing else to do beside fixing/investigating the linked issue.

**Comment by karfau** [comment]
Oh, that issue is in the original repo. So let's keep this on open. SOrry for the noise.

**Comment by karfau** [comment]
Spec references also for more test cases:
- https://www.w3.org/TR/xml11/#NT-S
- https://www.w3.org/TR/xml11/#sec-starttags

**Comment by karfau** [comment]
As reported in #263 the "allowed workspace that is not working as expected" includes line breaks.
