### ISSUE TITLE
Difference in spelling of `isHTMLMimeType` between implementation and type definition

### ISSUE THREAD

**Issue by marvinruder** [xmldom/xmldom#712]
**Describe the bug**
The implementation of the method verifying that a MIME type is `text/html` is named `isHTMLMimeType`, whereas its type definition is named `isHtmlMimeType`. This leads to typechecking errors and IDEs autocompleting the name of a non-existing method.

**To Reproduce**
Compare

https://github.com/xmldom/xmldom/blob/487680734e1ae8a785bec567959a5dfa5510aaad/index.d.ts#L23

against

https://github.com/xmldom/xmldom/blob/487680734e1ae8a785bec567959a5dfa5510aaad/lib/index.js#L5

and

https://github.com/xmldom/xmldom/blob/487680734e1ae8a785bec567959a5dfa5510aaad/lib/conventions.js#L278

**Expected behavior**
Type definition and implementation should match.

**Runtime & Version:**
xmldom version: 0.9.0
runtime version: N/A
other related software and version: N/A

**Comment by karfau** [comment]
Thx for reporting that. I think i recently successfully stuck to HTML and XML in all names, so the types should be fixed. Happy to take a PR for that but I'll also be able to fix it myself soon.
