### ISSUE TITLE
invalid regex group

### ISSUE THREAD

**Issue by retorquere** [xmldom/xmldom#714]
**Describe the bug**

at some point `reg` in `lib/grammar.js` is passed

```
"(?:SYSTEM[\\x20\\x09\\x0D\\x0A]+(?<SystemLiteralOnly>(?:\"[^\"]*\"|'[^']*')))"
```

I'm not sure whether `(?<` is meant to start a non-capturing group or a literal question mark, but a Zotero plugin I'm building errors out with "invalid regex group" in Zotero 6, likely because that builds on a fairly old version of Firefox.

**To Reproduce**

Does not reproduce on recent versions of javascript, sorry, but it should be easy to make it compatible with older javascript versions. This is new in 0.9.0

**Runtime & Version:**
xmldom version: 0.9.0
runtime version: Zotero 6.0

**Comment by retorquere** [comment]
Oh wait, it is a named capturing group! I'll see how I can work around this, sorry.

**Comment by karfau** [comment]
I'm not aware of that runtime and wether xmldom can "afford" to support it, but we use the examples directory and the related github actions to make sure the supported runtimes continue to work.
If you can provide a setup in a repo or in the github action workflow that you expect to work it is much easier to judge.
But 0.9.0 is the first version in years that dropped support for older runtimes (Node 10 and 12  are no longer supported) so I would prefer to only officially support "current versions" of "relevant" runtimes....
See the related discussion with poll that is linked in the release notes.

**Comment by retorquere** [comment]
I've found a way around it, and Zotero is phasing out Zotero 6 anyway. Zotero 6 is likely equivalent to node 12 or so in terms of language features supported. I wouldn't worry about it.
