### ISSUE TITLE
Missing types for most properties

### ISSUE THREAD

**Issue by Ponynjaa** [xmldom/xmldom#725]
**Describe the bug**
The typings within the `index.d.ts` file are incomplete.
Here's a list of typings that I found are missing in my project:
- Node::nodeType
- Node::lineNumber
- Node::columnNumber
- Node::textContent
- ProcessingInstruction::data
- ProcessingInstruction::target

I currently have to use @ts-ignore everywhere I use these properties, which is... not ideal.

**To Reproduce**
Try to use any of the previous properties on a Node/ProcessingInstruction.

**Expected behavior**
The typings in the `index.d.ts` should represent the implemented logic 1:1.

**Runtime & Version:**
xmldom version: 0.9.2
runtime version: Node v20.10.0
other related software and version: typescript v5.5.4

**Additional context**
@karfau seemed to have tried to sync the types with the logic in #717 however it seems like something went wrong here.

**Comment by karfau** [comment]
Thx for letting me know.
PRs are welcome.

I was sure we are not implementing `Node::textContent`...
Will check all the ones you listed.

**Comment by Ponynjaa** [comment]
I will probably open a PR soon.
You sure are implementing textContent https://github.com/xmldom/xmldom/blob/b6d02cf7a948979a03c8383eb5a0dde2bb1003cf/lib/dom.js#L2854

**Comment by karfau** [comment]
Ah, the darn "dynamic" prototype additions...

**Comment by ayZagen** [comment]
`Node.getAttribute` and `Node.getAttributeNS` also missing.

**Comment by Ponynjaa** [comment]
@ayZagen these only exist on `Element` actually. This is absolutely correct according to the [specs](https://dom.spec.whatwg.org/#ref-for-dom-element-getattribute).
