### ISSUE TITLE
parseFromString method hangs with an xsd on 0.9.x versions

### ISSUE THREAD

**Issue by luffynando** [xmldom/xmldom#748]
**Describe the bug**

Using the xsd attached to the example, the parseFromString method of DOMParser hangs and does not resolve the expected document element. I tested it with any of the versions starting from 0.9.0 and the error occurs, using version 0.8.10 everything works as it should.

**To Reproduce**
https://stackblitz.com/edit/node-rufjdp?file=index.ts

**Expected behavior**
Correct parse without hangs the process

**Runtime & Version:**
xmldom version: 0.9.x
runtime version: any

**Comment by mattiasw** [comment]
I think I might have the same problem. I have a similar-sized file that is parsed immediately with 0.8.10 but either hangs or takes a really long time with 0.9.3. I'm thinking it's the latter, that it takes really long to finish, because I tried different file sizes and noticed that at some point it started to take noticeably longer and longer to parse.
[huge.xml.zip](https://github.com/user-attachments/files/17289992/huge.xml.zip)

**Comment by karfau** [comment]
Thx for the reports.
I'm not in reach of a (real) computer for around a week, so any further investigation/information/profiling is helpful to have in advance.

Any hints that a certain kind if data triggers this, or is it rather some memory limits that are being reached when the documents reach a certain size? (Is there a difference when parsing the top level node with the first half of the children vs the second half? And so on...)

Does it make a difference to disable the `locator` in the DOMParser options?

Also if you find information that makes you think this might actually point into the direction of a security/DOS issue, please follow our security report guidelines: https://github.com/xmldom/xmldom?tab=security-ov-file

**Comment by luffynando** [comment]
Regarding disabling the `locator` option it has no impact on the reported issue

**Comment by karfau** [comment]
I'm able to reproduce the issue, for me the file shared by @luffynando takes around 11 min to parse using v0.9.3 (and < 1 sec on version 0.8.10).
I started profiling, but nothing obvious sticks out so far.

I'll try and `git bisect` it later to at least narrow down the change that causes it, but it needs more time.

If anybody has an idea how to do this, any support is much appreciated.

**Comment by karfau** [comment]
According to `git bisect` using your script (with a slight modification to call `clearTimeout` when the parsing is successful), commit 642c9e84b801ece8e54c82e860c5e4cb6c88f3c1 is the first commit that contains the regression, and I was able to narrow it down to a "unification" of the `appendChild` method between `Element` and `Document`, but I have not fully understood the issue/previous difference yet.

**Comment by karfau** [comment]
fix is released as 0.9.4
