### ISSUE TITLE
Add support for named exports

### ISSUE THREAD

**Issue by ajmas** [xmldom/xmldom#75]
The current docs indicate that to use the package you need to do:

```js
const DOMParser = require("xmldom").DOMParser;
```

It would be good to have named exports, so that this could be done:

```js
const { DOMParser } = require('xmldom');
```

or

```js
import { DOMParser } from 'xmldom'
```

This would not replace the current approach, but would be an addition allowing following the style of packaging that is being adopted.

**Comment by brodybits** [comment]
> ```js
> const { DOMParser } = require('xmldom');
> ```

That is already possible, I just tested it. I think the documented example should be updated.

> or
> 
> ```js
> import { DOMParser } from 'xmldom'
> ```

Right.

I would consider this to be a breaking change, maybe overlaps with the ES6 discussion (#76).

I think we would have to either set the module type in package.json, which seems to still be new, and not very well standardized, or add a pre-publish build step which I would rather avoid. I am actually not so enthusiastic at this point.

**Comment by ajmas** [comment]
Confirmed works, but not documented.

**Comment by karfau** [comment]
@ajmas When using this module in a typescript code base it is valid to write
```ts
import { DOMParser } from 'xmldom';
```
Just mentioning it for the sake of completeness.

**Comment by ajmas** [comment]
Would a PR for documentation update be welcome?

**Comment by brodybits** [comment]
> Would a PR for documentation update be welcome?

Yes and much appreciated
