### ISSUE TITLE
UTF-8-BOM Encoding leads to an error

### ISSUE THREAD

**Issue by JoinerDev** [xmldom/xmldom#753]
**Describe the bug**
When parsing a xml file with UTF-8-Encoding, the parser throws an error and is unable to continue. Is this intended behaviour?

This error was not present before i updated to 0.9.

The error reads:
"processing instruction at position 1 is an xml declaration which is only at the start of the document"

**To Reproduce**
Try to parse a file with UTF-8-BOM encoding.

**Expected behavior**
Parser can ignore UTF 8 BOM symbol EF BB BF.

**Runtime & Version:**
xmldom version: 0.9.3

**Comment by karfau** [comment]
@JoinerDev 
There are a lot of possible variables in the steps you describe, so I'm not sure I have a proper reproduction.
Even though there is no "specific code for handling BOM" in xmldom before 0.9.*, it seems to just "ignore" the BOM.

0.9.* is stricter regarding the input it receives. And I'm sorry to say, but handling all the possible string encoding options is out of scope for xmldom.

Here is how to fix it on your side (assuming that you are using node version >=11):

```js
const data = new TextDecoder().decode(fs.readFileSync('file-with-or-without-bom.xml'));
```

This way `data` no longer contains the BOM and can be passed to xmldom without any issues.

If this doesn't work for you, please provide a link to a repository that I can check out and run the code with, which can be one that you create for the purpose of this collaboration and only contains the minimal files required to reproduce.
