### ISSUE TITLE
Managing ownership

### ISSUE THREAD

**Issue by brodybits** [xmldom/xmldom#9]
When @kethinov added me to the xmldom package on npm, our agreement was to maintain the package in the new xmldom org on GitHub, with previous contributors & owners welcome to join if they wish to resume active maintenance.

I wanted to make this clear since I would like to invite at least one other member from Apache Cordova.

**Comment by brodybits** [comment]
As I said in #10, @timbru31 enabled 2FA for all members on this xmldom org, which I do fully support.

I hope this will not be a barrier for any previous maintainers if they want to join this xmldom org. In case 2FA does prove to be such a barrier, I think we should reconsider.

**Comment by kethinov** [comment]
I'm for it.

**Comment by timbru31** [comment]
> I hope this will not be a barrier for any previous maintainers if they want to join this xmldom org. In case 2FA does prove to be such a barrier, I think we should reconsider.

We should not reconsider, the new members should. 🙃
I'd like to remind about, e.g., the Gentoo "hack" because some members had 2FA not enabled: https://nakedsecurity.sophos.com/2018/06/29/linux-distro-hacked-on-github-all-code-considered-compromised/

**Comment by karfau** [comment]
@brodybits I hope you are fine with closing this issue as well. If not please propose some level of done. Thx
