### ISSUE TITLE
Infinite-loop error

### ISSUE THREAD

**Issue by natlibfi-arlehiko** [xmldom/xmldom#98]
When passing an object to DOMParser's `parseFromString` you'll get infinetely looping error:
```js
const {DOMParser} = require('xmldom');
new DOMParser().parseFromString({});
```
Obviously you shouldn't pass an object there, but still this should be fixed.

**Comment by brodybits** [comment]
Adding **help wanted** & **needs-investigation** labels. Maybe related to these:

- issue #97
- PR #43
- issue #55 (replace lib/sax.js, ideally with a better known & tested SAX parser)

**Comment by jesse-y** [comment]
Cheers - I'd be happy to have a go at fixing this, would you guys be alright with me raising a PR?

**Comment by brodybits** [comment]
A PR would be much appreciated, thanks.
